### Just My Socks ##
# https://justmysocks.net/members/index.php?rp=/knowledgebase/4/Which-server-IP-should-I-use.html

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s1.*?$'
replace = "United States GT1@"

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s2.*?$'
replace = "United States GT2@JMS"

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s3.*?$'
replace = "United States GIA@JMS"

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s4.*?$'
replace = "Japan SB@JMS"

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s5.*?$'
replace = "Netherlands GIA@JMS"

[[rename_node]]
match = '^JMS-\d+\u0040c\d+s801.*?$'
replace = "United States ECO@JMS"
